figure(1);
set(1,'position',[0 0,900,900]);
clf;

FCTD_rot_timer = timer;
s = false;

FCTD_rot_timer.StartFcn = 'disp(''Plot FCTD rotation begins now!'');';
FCTD_rot_timer.TimerFcn = [...
    'if s, '...
    'stop(FCTD_rot_timer); '...
    'delete(FCTD_rot_timer); '...
    'else, '...
    'try,'...
    'PlotUpAccumulation;'...
    'catch err,'...
    'display_error_stack(err); '...
    'end;'...
    'disp([''Done at '' datestr(now)]);'...
    'end;'];
FCTD_rot_timer.Period = 60*5;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
FCTD_rot_timer.BusyMode = 'drop';
FCTD_rot_timer.Name = 'FCTD_rot_timer';
FCTD_rot_timer.Tag = 'FCTD_rot_timer';
FCTD_rot_timer.StopFcn = 'clear(''rawDir'',''rawDirAway''); disp([datestr(now) '': Stopped FCTD_rot_timer'']);';
FCTD_rot_timer.ExecutionMode = 'fixedSpacing';
% FCTD_rot_timer.ExecutionMode = 'singleShot';
FCTD_rot_timer.TasksToExecute = Inf;
FCTD_rot_timer.ErrorFcn = 'disp(''%%%%%%%%%%%%% Error %%%%%%%%%%%%%'');';

start(FCTD_rot_timer);