function [Profile] = sort_profile(Profile);

% Standard order for Profile structure
fieldOrder = {'profNum';...
              'filenames';...
              'Meta_Data';...
              'varInfo';...
              'epsi';...
              'ctd';...
              'alt';...
              'act';...
              'vnav';...
              'gps';...
              'nbscan';...
              'nfft';...
              'nfftc';...
              'tscan';...
              'fpump';...
              'f';...
              'k';...
              'Cs1a3_full';...
              'Cs2a3_full';...
              'dnum';...
              'pr';...
              'w';...
              't';...
              's';...
              'th';...
              'sgth';...
              'kvis';...
              'ind_range_ctd';...
              'ind_range_epsi';...
              'epsilon';...
              'epsilon_co';...
              'sh_fc';...
              'chi';...
              'tg_fc';...
              'flag_tg_fc';...
              'Ps_volt_f';...
              'Ps_shear_k';...
              'Ps_shear_co_k';...
              'Pt_volt_f';...
              'Pt_Tg_k';...
              'Pa_g_f'};
          
 % Find the field names in Profile
 fieldNames = fields(Profile);
 
 % Find the fields in fieldOrder that also exist in fieldNames. Only keep
 % those. 
commonFields = fieldOrder(ismember(fieldOrder,fieldNames));

% Sort Profile in the order of commonFields
Profile = orderfields(Profile,commonFields);
          
end