% Initialize an epsi_class and an axes to use an input to plot_epsi_ctd
obj = epsi_class;
ax = axes;

EpsiPlot_time = timer;
EpsiPlot_time_Stop = false;

EpsiPlot_time.StartFcn = 'disp(''plotting epsi data...'');';
EpsiPlot_time.TimerFcn = [...
    'if EpsiPlot_time_Stop, '...
    'stop(EpsiPlot_time); '...
    'delete(EpsiPlot_time); '...
    'else, '...
    'disp([datestr(now) '': Converting ascii data to mat...!'']); '...
    'try, '...
    'obj.f_getLastData;, '...
    'ax = epsiPlot_epsi_ctd_alt_timeseries(obj,0,ax); '...
    'catch err, '...
    'disp(err); '...
    'end; '...
    'end;'];
EpsiPlot_time.Period = 10;
EpsiPlot_time.BusyMode = 'drop';
EpsiPlot_time.Name = 'EpsiPlot_time';
EpsiPlot_time.Tag = 'EpsiPlot_time';
EpsiPlot_time.StopFcn = 'disp([datestr(now) '': Stopped EpsiPlot_time'']);';
EpsiPlot_time.ExecutionMode = 'fixedSpacing';
% EpsiPlot_time.ExecutionMode = 'singleShot';
EpsiPlot_time.TasksToExecute = Inf;
EpsiPlot_time.ErrorFcn = 'disp(''%%%%%%%%%%%%% Error %%%%%%%%%%%%%'');';

start(EpsiPlot_time);